programs:
    exception:
        command: /bin/sh
        numprocs: 1
        retry: 3
        exitcodes:
            - 0
            - 1
        autostart: true
        autorestart: onerror
        stopsignal: TERM
        priority: 5
        stdout_logfile_maxbytes: 100
        stdout_logfile_backups: 30
    solo:
        command: /bin/bash -c "sleep 10"
        numprocs: 10
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: TERM
        priority: 1
    printeur_fou:
        command: cat /dev/random
        startsecs: 0
        numprocs: 5
        priority: 7
        stdout_logfile_maxbytes: 1024
        stdout_logfile_backups: 3

server:
    daemon: false
    logfile: /tmp/taskmaster.log
    loglevel: DEBUG
    log_discord: true
    loglevel_discord: INFO
    logfile_maxbytes: 4096
    logfile_backups: 3

socket:
    enable: true
    socketpath: /tmp/taskmaster.sock
    umask: 077
