programs:
    exception:
        command: /bin/sh
        numprocs: 3
        retry: 3
        exitcodes:
            - 0
            - 1
        autostart: false
        autorestart: onerror
        stopsignal: TERM
        priority: 5
    solo:
        command: sleep 5
        numprocs: 1
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: TERM
        priority: 1

server:
    daemon: false
    logfile: taskmaster.log
    loglevel: DEBUG
    log_discord: true
    loglevel_discord: INFO

socket:
    enable: true
    socketpath: /tmp/taskmaster.sock
    umask: 077
