programs:
    exception:
        command: /bin/sh
        numprocs: 1
        startretries: 3
        exitcodes:
            - 0
            - 1
        autostart: true
        autorestart: onerror
        stopsignal: TERM
        priority: 5
        stdout_logfile_maxbytes: 100
        stdout_logfile_backups: 30
    solo:
        command: /bin/bash -c "sleep 10"
        numprocs: 1
        startretries: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: TERM
        priority: 1
    printeur_fou:
        command: cat /dev/random
        numprocs: 1
        priority: 7
        stdout_logfile_maxbytes: 1024
        stdout_logfile_backups: 3
    nullos:
      command: This is not a valid command
      numprocs: 1
      startretries: 0
      autostart: true
      priority: 2

server:
    daemon: false
    logfile: /tmp/taskmaster.log
    loglevel: DEBUG
    log_discord: true
    loglevel_discord: INFO
    logfile_maxbytes: 4096
    logfile_backups: 3
    user: parrot

socket:
    enable: true
    socketpath: /tmp/taskmaster.sock
    umask: 077
