programs:
    exception:
        command: /bin/sh -c "echo 32; sleep 5"
        numprocs: 2
        retry: 3
        umask: 0o022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: USR2
        priority: 3
    echoeing:
        command: /bin/sh -c "echo 32; sleep 5"
        numprocs: 2
        retry: 3
server:
    unixsocket:
        file: /mnt/nfs/homes/bdetune/taskmasterd.sock
        chmod: 0o744
        username: bdetune
        chown: :user
    logfile: logs/taskmaster.log
    loglevel: WARN
    logfile_maxbytes: 1024
    umask: 26
