programs:
    exception:
        command: /bin/sh
        numprocs: 2
        retry: 3
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: TERM
        priority: 3
    solo:
        command: sleep 5
        numprocs: 1
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: TERM
        priority: 5

server:
    daemon: false
    logfile: taskmaster.log
    loglevel: DEBUG

socket:
    enable: true
    socketpath: /tmp/taskmaster.sock
    umask: 077
