programs:
    exception:
        command: cat ls; sleep 5
        numprocs: 2
        retry: 3
        umask: 0o022
    echoeing:
        command: echo 1
        retry: 3
        umask: 0o022
server:
    connection: Unix