programs:
    exception:
        command: /bin/sh
        numprocs: 2
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: KILL
        priority: 3
    echoeing:
        command: echo 1
        retry: 3
        umask: 027
        user: bdetune
        workingdir: /
        env:
            PATH: ""
            PATH: "/"
            pwd: "~"
server:
    unixsocket:
        file: /mnt/nfs/homes/bdetune/taskmasterd.sock
        chmod: 0o744
        username: bdetune
        chown: :user
    logfile: logs/taskmaster.log
    loglevel: DEBUG
