programs:
    exception:
        command: /bin/sh -c "echo 32; sleep 5"
        numprocs: 2
        retry: 3
        umask: 0o022
        exitcodes:
            - 1
        autorestart: onerror
        stopsignal: USR2
        priority: 3
    echoeing:
        command: echo 1
        retry: 3
        umask: 0o027
        user: bdetune
        workingdir: /
        env:
            PATH: ""
            PATH: "/"
            pwd: "~"
server:
    unixsocket:
        file: /mnt/nfs/homes/bdetune/taskmasterd.sock
        chmod: 0o744
        username: bdetune
        chown: :user
    logfile: /mnt/nfs/homes/bdetune/taskmaster.log
    loglevel: ERRO