programs:
    exception:
        command: /bin/sh -c "echo 32; sleep 5"
        numprocs: 2
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: USR2
        priority: 3
    echoeing:
        command: echo 1
        retry: 3
        umask: 027
        user: bdetune
        workingdir: /
        env:
            PATH: ""
            PATH: "/"
            pwd: "~"
server:
    unixsocket:
        file: /mnt/nfs/homes/bdetune/taskmasterd.sock
        chmod: 0o744
        username: bdetune
        chown: :user
    daemon: false
    logfile: taskmaster.log
    loglevel: DEBUG

socket:
    enable: true
    socketpath: /mnt/nfs/homes/bdetune/42Cursus/42Unix/taskmaster/taskmaster.sock
    uid: bdetune
    umask: 077
