programs:
    exception:
        command: /bin/sh
        numprocs: 11
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: KILL
        priority: 3
server:
    unixsocket:
        file: /mnt/nfs/homes/bdetune/taskmasterd.sock
        chmod: 0o744
        username: bdetune
        chown: :user
    daemon: false
    logfile: taskmaster.log
    loglevel: DEBUG

socket:
    enable: true
    socketpath: /mnt/nfs/homes/bdetune/42Cursus/42Unix/taskmaster/taskmaster.sock
    uid: bdetune
    umask: 077
