programs:
    exception:
        command: /bin/sh
        numprocs: 11
        retry: 3
        umask: 022
        exitcodes:
            - 0
            - 1
        autorestart: onerror
        stopsignal: KILL
        priority: 3
server:
    daemon: true
    logfile: taskmaster.log
    loglevel: DEBUG

socket:
    enable: true
    socketpath: /tmp/taskmaster.sock
    umask: 077
